---
version: '3.7'

# example stack-compose file for a docker swarm setup
# 
# environemnt variables:
#
# WEB_ALIAS_DOMAIN:   domain of the sso service
# WEB_TITLE:          page title of the password mask

services:
  webserver:
    image: webdevops/php-nginx:7.4
    environment:
      WEB_ALIAS_DOMAIN: ${WEB_ALIAS_DOMAIN}
    deploy:
      labels:
        - 'traefik.port=80'
        - 'traefik.frontend.redirect.entryPoint=https'
        - 'traefik.docker.network=Traefik_traefik-net'
        - 'traefik.frontend.rule=Host:${WEB_ALIAS_DOMAIN}'
    networks:
      - Traefik_traefik-net
    volumes:
      - /yourprojectpath/sso/credentials.yml:/app/credentials.yml
    logging:
      options:
        max-size: '100m'
        max-file: '5'
      driver: json-file

networks:
  Traefik_traefik-net:
    external: true
